
  spring:
    datasource:
      url: jdbc:mysql://13.232.157.56:3306/scribble_space
      password: Sh73shfbl
      username: Nishant
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update




